---

- name: Install fahclient
  block:

    - name: Check if fahclient is already installed
      command: rpm -qi fahclient
      args:
        warn: false
      register: fahclient_installed
      failed_when: false
      changed_when: false

    - name: Download fahclient
      get_url:
        url: "{{ folding_at_home_fahclient_url[ansible_os_family] }}"
        dest: /var/tmp/fahclient.rpm
      when: fahclient_installed.rc == 1

    - name: Install procps dependency (needed by init script)
      yum:
        name: procps
        state: present

    - name: Install fahclient
      yum:
        name: /var/tmp/fahclient.rpm
        state: present
      become: true
      become_user: root
      when: fahclient_installed.rc == 1

  when: folding_at_home_install_fahclient

- name: Install fahcontrol
  block:

    - name: Check if fahcontrol is already installed
      command: rpm -qi fahcontrol
      args:
        warn: false
      register: fahcontrol_installed
      failed_when: false
      changed_when: false

    - name: Download fahcontrol
      get_url:
        url: "{{ folding_at_home_fahcontrol_url[ansible_os_family] }}"
        dest: /var/tmp/fahcontrol.rpm
      when: fahcontrol_installed.rc == 1

    - name: Install fahcontrol
      yum:
        name: /var/tmp/fahcontrol.rpm
        state: present
      become: true
      become_user: root
      when: fahcontrol_installed.rc == 1

  when: folding_at_home_install_fahcontrol

- name: Install fahviewer
  block:

    - name: Check if fahviewer is already installed
      command: rpm -qi fahviewer
      args:
        warn: false
      register: fahviewer_installed
      failed_when: false
      changed_when: false

    - name: Download fahviewer
      get_url:
        url: "{{ folding_at_home_fahviewer_url[ansible_os_family] }}"
        dest: /var/tmp/fahviewer.rpm
      when: fahviewer_installed.rc == 1

    - name: Install fahviewer
      yum:
        name: /var/tmp/fahviewer.rpm
        state: present
      become: true
      become_user: root
      when: fahviewer_installed.rc == 1

  when: folding_at_home_install_fahviewer

- name: Clean up .rpm files
  file:
    dest: "{{ folding_at_home_tmp_dir }}/{{ item }}.rpm"
    state: absent
  with_items:
    - fahclient
    - fahcontrol
    - fahviewer
